package service;

import model.CartItem;
import model.Collaboration;
import model.Event;
import model.Reservation;
import org.apache.pdfbox.pdmodel.*;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.graphics.image.LosslessFactory;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;

import java.awt.image.BufferedImage;
import java.io.File;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Generates PDF tickets (with QR code) and order receipts using Apache PDFBox.
 */
public class PdfService {

    private final QRCodeService qrService = new QRCodeService();

    // ── EVENT TICKET ──────────────────────────────────────────────────────

    public void generateTicket(Reservation res, Event event, File file) throws Exception {
        try (PDDocument doc = new PDDocument()) {
            PDPage page = new PDPage(new PDRectangle(PDRectangle.A5.getWidth(), PDRectangle.A5.getHeight()));
            doc.addPage(page);

            PDType1Font bold    = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            PDType1Font regular = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

            float W      = page.getMediaBox().getWidth();
            float H      = page.getMediaBox().getHeight();
            float margin = 36;
            float inner  = W - 2 * margin;

            try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {
                // Dark background
                fillRect(cs, 0, 0, W, H, 5, 5, 7);

                // Red accent stripe at top
                fillRect(cs, 0, H - 8, W, 8, 232, 50, 10);

                float y = H - 36;

                // Header
                drawText(cs, bold, 20, margin, y, 232, 50, 10, "EVENTO  ·  EVENT TICKET");
                y -= 26;
                drawText(cs, regular, 9, margin, y, 58, 61, 82,
                        LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")));
                y -= 18;

                // Separator
                drawLine(cs, margin, y, margin + inner, y, 1.5f, 232, 50, 10);
                y -= 22;

                // Event name
                String title = event != null && event.getTitre() != null ? event.getTitre() : "Event";
                drawText(cs, bold, 16, margin, y, 240, 242, 248, truncate(title, 46));
                y -= 22;

                if (event != null) {
                    if (event.getDateHeure() != null)
                        drawDetail(cs, bold, regular, margin, y -= 16, "DATE",
                                event.getDateHeure().format(DateTimeFormatter.ofPattern("EEE, dd MMM yyyy  •  HH:mm")));
                    if (event.getVenue() != null)
                        drawDetail(cs, bold, regular, margin, y -= 16, "VENUE", event.getVenue());
                    if (event.getGenre() != null)
                        drawDetail(cs, bold, regular, margin, y -= 16, "GENRE", event.getGenre());
                }
                drawDetail(cs, bold, regular, margin, y -= 16, "SEATS",  String.valueOf(res.getNombrePlaces()));
                drawDetail(cs, bold, regular, margin, y -= 16, "STATUS", res.getStatut() != null ? res.getStatut().toUpperCase() : "PENDING");
                drawDetail(cs, bold, regular, margin, y -= 16, "REF #",  "EVT-" + res.getId());
                y -= 24;

                // QR Code
                String qrContent = "EVENTO|TICKET:" + res.getId()
                        + "|EVENT:" + (event != null ? event.getTitre() : "")
                        + "|USER:" + res.getUserId()
                        + "|SEATS:" + res.getNombrePlaces();
                BufferedImage qr = qrBuffered(qrContent, 140);
                if (qr != null) {
                    PDImageXObject img = LosslessFactory.createFromImage(doc, qr);
                    cs.drawImage(img, margin, y - 140, 140, 140);

                    drawText(cs, regular, 8, margin + 154, y - 50,  58, 61, 82, "Scan at entrance");
                    drawText(cs, regular, 8, margin + 154, y - 64,  58, 61, 82, "to validate ticket.");
                    drawText(cs, regular, 7, margin + 154, y - 84,  36, 38, 50, "Generated by EVENTO App");
                }

                // Bottom stripe
                fillRect(cs, 0, 0, W, 8, 232, 50, 10);
            }
            doc.save(file);
        }
    }

    // ── ORDER RECEIPT ─────────────────────────────────────────────────────

    public void generateReceipt(List<CartItem> items, double total, int orderRef, File file) throws Exception {
        try (PDDocument doc = new PDDocument()) {
            PDPage page = new PDPage(new PDRectangle(PDRectangle.A5.getWidth(), PDRectangle.A5.getHeight()));
            doc.addPage(page);

            PDType1Font bold    = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            PDType1Font regular = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

            float W = page.getMediaBox().getWidth(), H = page.getMediaBox().getHeight();
            float margin = 36, inner = W - 2 * margin;

            try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {
                fillRect(cs, 0, 0, W, H, 5, 5, 7);
                fillRect(cs, 0, H - 8, W, 8, 200, 255, 0);

                float y = H - 36;

                drawText(cs, bold, 20, margin, y, 200, 255, 0, "EVENTO  ·  ORDER RECEIPT");
                y -= 22;
                drawText(cs, regular, 9, margin, y, 58, 61, 82,
                        "Order #ORD-" + orderRef + "  ·  " +
                        LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")));
                y -= 16;
                drawLine(cs, margin, y, margin + inner, y, 1f, 28, 28, 40);
                y -= 18;

                // Column headers
                drawText(cs, bold, 9, margin, y, 99, 102, 241, "ITEM");
                drawText(cs, bold, 9, margin + inner - 90, y, 99, 102, 241, "QTY");
                drawText(cs, bold, 9, margin + inner - 45, y, 99, 102, 241, "TOTAL");
                y -= 14;
                drawLine(cs, margin, y, margin + inner, y, 0.5f, 28, 28, 40);
                y -= 14;

                for (CartItem ci : items) {
                    String name = truncate(ci.getProduct().getName(), 34);
                    drawText(cs, regular, 10, margin, y, 200, 205, 223, name);
                    drawText(cs, regular, 10, margin + inner - 90, y, 200, 205, 223, "x" + ci.getQuantity());
                    drawText(cs, regular, 10, margin + inner - 45, y, 200, 205, 223,
                            String.format("%.2f", ci.getSubtotal()));
                    y -= 16;
                }

                y -= 8;
                drawLine(cs, margin, y, margin + inner, y, 1.5f, 200, 255, 0);
                y -= 18;
                drawText(cs, bold, 14, margin, y, 200, 255, 0, "TOTAL");
                drawText(cs, bold, 14, margin + inner - 72, y, 200, 255, 0,
                        String.format("%.2f TND", total));
                y -= 36;
                drawText(cs, regular, 8, margin, y, 36, 38, 50, "Thank you for your purchase! — EVENTO Music Experience");

                fillRect(cs, 0, 0, W, 8, 200, 255, 0);
            }
            doc.save(file);
        }
    }

    // ── COLLABORATION REPORT ───────────────────────────────────────────────

    public void generateCollaborationReport(Collaboration collab, int impressions, int clicks, String ctr, File file) throws Exception {
        try (PDDocument doc = new PDDocument()) {
            PDPage page = new PDPage(new PDRectangle(PDRectangle.A5.getWidth(), PDRectangle.A5.getHeight()));
            doc.addPage(page);

            PDType1Font bold    = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            PDType1Font regular = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

            float W = page.getMediaBox().getWidth(), H = page.getMediaBox().getHeight();
            float margin = 36, inner = W - 2 * margin;

            try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {
                // Dark background
                fillRect(cs, 0, 0, W, H, 5, 5, 7);
                // Purple accent stripe at top
                fillRect(cs, 0, H - 8, W, 8, 128, 0, 128);

                float y = H - 36;

                drawText(cs, bold, 20, margin, y, 128, 0, 128, "COLLABORATION REPORT");
                y -= 26;
                drawText(cs, regular, 9, margin, y, 58, 61, 82,
                        "Generated on: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")));
                y -= 18;

                drawLine(cs, margin, y, margin + inner, y, 1.5f, 128, 0, 128);
                y -= 22;

                drawText(cs, bold, 16, margin, y, 240, 242, 248, truncate(collab.getTitle(), 46));
                y -= 22;

                drawDetail(cs, bold, regular, margin, y -= 16, "PARTNER ID", String.valueOf(collab.getPartnerId()));
                drawDetail(cs, bold, regular, margin, y -= 16, "TYPE", collab.getType());
                drawDetail(cs, bold, regular, margin, y -= 16, "POSITION", collab.getPosition());
                drawDetail(cs, bold, regular, margin, y -= 16, "STATUS", collab.getStatus());
                
                String dates = (collab.getStartDate() != null ? collab.getStartDate().toString() : "") + " to " +
                               (collab.getEndDate() != null ? collab.getEndDate().toString() : "");
                drawDetail(cs, bold, regular, margin, y -= 16, "DATES", dates);
                drawDetail(cs, bold, regular, margin, y -= 16, "EST. PRICE", collab.getPrice() != null ? collab.getPrice() + " TND" : "N/A");
                y -= 24;

                drawLine(cs, margin, y, margin + inner, y, 0.5f, 28, 28, 40);
                y -= 24;

                drawText(cs, bold, 14, margin, y, 200, 255, 0, "PERFORMANCE ANALYTICS");
                y -= 20;

                drawDetail(cs, bold, regular, margin, y -= 16, "IMPRESSIONS", String.valueOf(impressions));
                drawDetail(cs, bold, regular, margin, y -= 16, "CLICKS", String.valueOf(clicks));
                drawDetail(cs, bold, regular, margin, y -= 16, "PERF. GRADE", ctr);

                y -= 24;

                // QR Code
                String qrContent = collab.getLinkUrl() != null ? collab.getLinkUrl() : "https://evento.tn";
                BufferedImage qr = qrBuffered(qrContent, 100);
                if (qr != null) {
                    PDImageXObject img = LosslessFactory.createFromImage(doc, qr);
                    cs.drawImage(img, margin, y - 100, 100, 100);
                    drawText(cs, regular, 8, margin + 110, y - 50,  58, 61, 82, "Scan to visit the ad link");
                }

                fillRect(cs, 0, 0, W, 8, 128, 0, 128);
            }
            doc.save(file);
        }
    }

    // ── Low-level helpers ─────────────────────────────────────────────────

    private void fillRect(PDPageContentStream cs, float x, float y, float w, float h,
                           int r, int g, int b) throws Exception {
        cs.setNonStrokingColor(r / 255f, g / 255f, b / 255f);
        cs.addRect(x, y, w, h);
        cs.fill();
    }

    private void drawText(PDPageContentStream cs, PDType1Font font, float size,
                          float x, float y, int r, int g, int b, String text) throws Exception {
        cs.setNonStrokingColor(r / 255f, g / 255f, b / 255f);
        cs.beginText();
        cs.setFont(font, size);
        cs.newLineAtOffset(x, y);
        cs.showText(text);
        cs.endText();
    }

    private void drawLine(PDPageContentStream cs, float x1, float y1, float x2, float y2,
                          float width, int r, int g, int b) throws Exception {
        cs.setStrokingColor(r / 255f, g / 255f, b / 255f);
        cs.setLineWidth(width);
        cs.moveTo(x1, y1);
        cs.lineTo(x2, y2);
        cs.stroke();
    }

    private void drawDetail(PDPageContentStream cs, PDType1Font bold, PDType1Font regular,
                            float x, float y, String label, String value) throws Exception {
        drawText(cs, bold,    9,  x,      y, 99,  102, 241, label + ":");
        drawText(cs, regular, 10, x + 58, y, 200, 205, 223, truncate(value, 50));
    }

    private BufferedImage qrBuffered(String content, int size) {
        try {
            com.google.zxing.qrcode.QRCodeWriter writer = new com.google.zxing.qrcode.QRCodeWriter();
            java.util.Map<com.google.zxing.EncodeHintType, Object> hints = new java.util.HashMap<>();
            hints.put(com.google.zxing.EncodeHintType.CHARACTER_SET, "UTF-8");
            hints.put(com.google.zxing.EncodeHintType.MARGIN, 1);
            com.google.zxing.common.BitMatrix matrix =
                    writer.encode(content, com.google.zxing.BarcodeFormat.QR_CODE, size, size, hints);
            return com.google.zxing.client.j2se.MatrixToImageWriter.toBufferedImage(matrix);
        } catch (Exception e) { return null; }
    }

    private String truncate(String s, int max) {
        if (s == null) return "";
        return s.length() > max ? s.substring(0, max) + "…" : s;
    }
}
